David branch
AlvarezR1/team-ogiogi pull request #9
Opened 2021-12-13 01:00 UTC by Davidav18

2021-12-13 02:52 UTC, AlvarezR1 commented on css/style.css
> +<<<<<<< Updated upstream
Como único detalle, la linea 33, se que esto no afecta en nada al proyecto, pero para mantener nuestra área de trabajo en orden, si me apoyas quitándola, gracias.

2021-12-13 02:53 UTC, AlvarezR1 commented on css/style.css
> +=======
De igual manera este, como en la linea `33`

2021-12-13 02:54 UTC, AlvarezR1 commented on css/style.css
> +>>>>>>> Stashed changes
Mismo detalle de la linea `33`

2021-12-13 02:54 UTC, AlvarezR1 commented on css/style.css
> +<<<<<<< Updated upstream
Mismo detalle de la linea `33`

2021-12-13 02:55 UTC, AlvarezR1 commented on css/style.css
> +=======
Mismo detalle de la linea `33`

2021-12-13 02:55 UTC, AlvarezR1 commented on css/style.css
> +=======
Mismo detalle de la linea `33`

2021-12-13 02:55 UTC, AlvarezR1 commented on css/style.css
> +>>>>>>> Stashed changes
Mismo detalle de la linea `33`

2021-12-13 02:56 UTC, AlvarezR1 commented on index.html
> +<<<<<<< Updated upstream
aquí lo mismo con lo del Css, solo es si me apoyas quitandolo, gracias.

2021-12-13 02:56 UTC, AlvarezR1 commented on index.html
> +=======
aquí lo mismo con lo del Css, solo es si me apoyas quitandolo, gracias.

2021-12-13 02:56 UTC, AlvarezR1 commented on index.html
> +>>>>>>> Stashed changes
aquí lo mismo con lo del Css, solo es si me apoyas quitandolo, gracias.

2021-12-13 02:56 UTC, AlvarezR1 commented on index.html
> +<<<<<<< Updated upstream
aquí lo mismo con lo del Css, solo es si me apoyas quitandolo, gracias.

2021-12-13 02:57 UTC, AlvarezR1 commented on index.html
> +=======
aqui desde la linea 97 hasta la 105, es solamente eliminar esto para que nuestro codigo sea mas limpio y ordenado

2021-12-13 02:59 UTC, AlvarezR1 requested changes
Corregir únicos detalles, no afectan al proyecto, pero prefiero que todo se vea ordenado y limpo.

2021-12-13 21:29 UTC, merged

2021-12-14 05:14 UTC, Davidav18 commented on css/style.css
> +<<<<<<< Updated upstream
Ya fueron arreglados todos los problemas puedo dejar resueltos los comments